FROM python:3.10-slim

# Cài đặt GCC để biên dịch Brute-force engine (C)
RUN apt-get update && \
    apt-get install -y gcc make && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

# Cài đặt thư viện Python (NumPy, Matplotlib, Pytest...)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Giữ container luôn chạy ngầm để có thể bash/exec vào chạy script tấn công
CMD ["tail", "-f", "/dev/null"]